COUNTRY_TO_CONTINENT = {
    'CANADA': 'North America', 'EGYPT': 'Africa', 'ZAMBIA': 'Africa', 'INDIA': 'Asia',
    'SOMALIA': 'Africa', 'RUSSIAN FEDERATION': 'Europe/Asia', 'LEBANON': 'Asia', 'MOZAMBIQUE': 'Africa',
    'LATVIA': 'Europe', 'UNITED ARAB EMIRATES': 'Asia', 'SEYCHELLES': 'Africa', 'HAITI': 'North America',
    'AUSTRALIA': 'Oceania', 'BAHAMAS': 'North America', 'ARUBA': 'North America', 'BELARUS': 'Europe',
    'GHANA': 'Africa', 'ANGOLA': 'Africa', 'PAPUA NEW GUINEA': 'Oceania', 'BURUNDI': 'Africa',
    'VIET NAM': 'Asia', 'TONGA': 'Oceania', 'FIJI': 'Oceania', 'FRENCH POLYNESIA': 'Oceania',
    'YEMEN': 'Asia', 'MADAGASCAR': 'Africa', 'BOLIVIA': 'South America', 'ETHIOPIA': 'Africa',
    'SWITZERLAND': 'Europe', 'PERU': 'South America', 'ICELAND': 'Europe', 'JAMAICA': 'North America',
    'SUDAN': 'Africa', 'DJIBOUTI': 'Africa', 'SRI LANKA': 'Asia', 'MAURITANIA': 'Africa',
    'SINGAPORE': 'Asia', 'PANAMA': 'North America', 'GAMBIA': 'Africa', 'GUINEA': 'Africa',
    'SERBIA': 'Europe', 'COSTA RICA': 'North America', 'KUWAIT': 'Asia', 'RWANDA': 'Africa',
    'SWAZILAND': 'Africa', 'MEXICO': 'North America', 'NIGERIA': 'Africa', 'SIERRA LEONE': 'Africa',
    'TOGO': 'Africa', 'NICARAGUA': 'North America', 'TAIWAN, PROVINCE OF CHINA': 'Asia', 'ROMANIA': 'Europe',
    'BHUTAN': 'Asia', 'BARBADOS': 'North America', 'CHINA': 'Asia', 'SYRIAN ARAB REPUBLIC': 'Asia',
    'NEPAL': 'Asia', 'TUNISIA': 'Africa', 'MACAU': 'Asia', 'KOREA, REPUBLIC OF': 'Asia',
    'UNITED KINGDOM': 'Europe', 'MOROCCO': 'Africa', 'CAYMAN ISLANDS': 'North America',
    'COLOMBIA': 'South America', 'VANUATU': 'Oceania', 'SURINAME': 'South America', 'DOMINICA': 'North America',
    'LIBERIA': 'Africa', 'NEW ZEALAND': 'Oceania', 'BRAZIL': 'South America', 'GUYANA': 'South America',
    'ARGENTINA': 'South America', 'INDONESIA': 'Asia', 'CYPRUS': 'Asia', 'HUNGARY': 'Europe',
    'BULGARIA': 'Europe', 'TURKEY': 'Asia', 'BAHRAIN': 'Asia', 'THAILAND': 'Asia',
    'CZECH REPUBLIC': 'Europe', 'DOMINICAN REPUBLIC': 'North America', 'SOLOMON ISLANDS': 'Oceania',
    'HONG KONG': 'Asia', 'BRUNEI DARUSSALAM': 'Asia', 'NAMIBIA': 'Africa', 'QATAR': 'Asia',
    'ALGERIA': 'Africa', 'JORDAN': 'Asia', 'ISRAEL': 'Asia', 'OMAN': 'Asia', 'URUGUAY': 'South America',
    'POLAND': 'Europe', 'HONDURAS': 'North America', 'SWEDEN': 'Europe', 'BOTSWANA': 'Africa',
    'CAMBODIA': 'Asia', 'ZIMBABWE': 'Africa', 'MALAWI': 'Africa', 'MYANMAR': 'Asia',
    'PHILIPPINES': 'Asia', 'ALBANIA': 'Europe', 'BANGLADESH': 'Asia', 'MALDIVES': 'Asia',
    'DENMARK': 'Europe', 'NORWAY': 'Europe', 'LIBYAN ARAB JAMAHIRIYA': 'Africa', 'BELIZE': 'North America',
    'SAMOA': 'Oceania', 'PAKISTAN': 'Asia', 'NETHERLANDS ANTILLES': 'North America',
    'TANZANIA, UNITED REPUBLIC OF': 'Africa', 'VENEZUELA': 'South America', 'CHILE': 'South America',
    'BERMUDA': 'North America', 'SOUTH AFRICA': 'Africa', 'UGANDA': 'Africa', 'JAPAN': 'Asia',
    'EURO': 'Europe', 'SAUDI ARABIA': 'Asia', 'IRAQ': 'Asia', 'MAURITIUS': 'Africa',
    'GUATEMALA': 'North America', 'KENYA': 'Africa', 'LAO PEOPLE\'S DEMOCRATIC REP': 'Asia',
    'CENTRAL AFRICAN REPUBLIC': 'Africa', 'EL SALVADOR': 'North America', 'MALAYSIA': 'Asia',
    'SAO TOME AND PRINCIPE': 'Africa', 'CAPE VERDE': 'Africa', 'PARAGUAY': 'South America',
    'KAZAKHSTAN': 'Asia', 'AZERBAIJAN': 'Asia', 'IRAN (ISLAMIC REPUBLIC OF)': 'Asia',
    'UKRAINE': 'Europe', 'CROATIA': 'Europe', 'TRINIDAD AND TOBAGO': 'North America'
}